name: Generate CLOC Badge

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure all branches are fetched

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cloc jq

    - name: Run cloc
      run: |
        cloc --json . > /tmp/cloc_temp.json

    - name: Switch to gh-pages branch
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout gh-pages

    - name: Copy cloc.json to gh-pages branch
      run: |
        cp /tmp/cloc_temp.json cloc.json

    - name: Update badge data
      run: |
        LINES=$(jq '.SUM.code' cloc.json)
        cat <<EOF > cloc.json
        {
          "schemaVersion": 1,
          "label": "Total Lines",
          "message": "$LINES",
          "color": "blue"
        }
        EOF

    - name: Commit badge data
      run: |
        git add cloc.json
        git commit -m "Update cloc data" || echo "No changes to commit"
        git push origin gh-pages
